import Head from "next/head";
import type { NextPage } from "next";

import MainLayout from "../layout/MainLayout";
import Hero from "../components/home/Hero";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<MainLayout>
				<Hero />
			</MainLayout>
		</>
	);
};

export default Home;
